config/routes.rb
# encoding: utf-8

# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.


Tea::Application.routes.draw do

  root to: 'tea_sessions#new'
  match 'manifests/loader', to: 'manifests#loader'
  match 'manifests/reader.appcache', to: 'manifests#reader', format: :text

  devise_for :users
  resources :tea_sessions, only: [:new, :create, :destroy]

  namespace :ebook do
    match 'epub', to: 'epubs#reader', as: :epub_reader, format: :html
    match 'epub_sandbox', to: 'epubs#reader_sandbox', as: :epub_reader_sandbox, format: :html
    resources :epubs do
      resources :components, only: [:show], controller: 'epub/components'
      resources :chapters, only: [:index], controller: 'epub/chapters'
    end
  end

  scope :offline, as: :offline, path: :offline do
    namespace :ebook do
      match 'epub', to: 'epubs#reader', format: :html, offline: true
      match 'epub_sandbox', to: 'epubs#reader_sandbox', format: :html, offline: true
      match 'epubs', to: 'epubs#index', format: :html, offline: true
    end
  end

  resources :books do
    member do
      get :reading_position, to: 'reading_position#show'
      put :reading_position, to: 'reading_position#update'
    end
    resources :bookmarks
    resources :annotations, except: [:new, :edit]
  end

  devise_for :admins
  namespace :admin do
    root to: 'home#index'
    resources :booksellers
  end
  mount Resque::Server.new, at: "/resque", as: :resque

end

app/models/bookmark.rb
# encoding: utf-8

# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.


class Bookmark < BookLocation
  attr_accessible :book, :component_name, :start_xpath, :device, :epub_cfi
end

app/controllers/bookmarks_controller.rb
# encoding: utf-8

# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.


class BookmarksController < ApplicationController
  helper_method :book, :bookmarks

  before_filter :authenticate_user!

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = book.bookmarks

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookmarks }
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    @bookmark = bookmark

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/new
  # GET /bookmarks/new.json
  def new
    @bookmark = book.bookmarks.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/1/edit
  def edit
    @bookmark = bookmark
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = book.bookmarks.new(params[:bookmark])
    @bookmark.user = current_user

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to book_bookmark_path(book, bookmark), notice: 'Bookmark was successfully created.' }
        format.json { render json: @bookmark, status: :created, location: @bookmark }
      else
        format.html { render action: "new" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookmarks/1
  # PUT /bookmarks/1.json
  def update
    @bookmark = bookmark

    respond_to do |format|
      if @bookmark.update_attributes(params[:bookmark])
        format.html { redirect_to book_bookmark_path(book, bookmark), notice: 'Bookmark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    bookmark.destroy

    respond_to do |format|
      format.html { redirect_to book_bookmarks_url(book) }
      format.json { head :no_content }
    end
  end

  def reading_position
    @reading_position = current_user.reading_position(book)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reading_position }
    end
  end

protected

  def book
    @book ||= current_user.books.find(params[:book_id] || params[:epub_id])
  end

  def bookmark
    return @bookmark if @bookmark

    @bookmark = book.bookmarks.find(params[:id])
    @bookmark.user = current_user

    @bookmark
  end
end

app/views/bookmarks/_form.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



= simple_form_for(book_bookmark_path(@bookmark.book.to_param, @bookmark.to_param)) do |f|
  = f.error_notification

  .form-inputs
    = f.input :start_xpath
    = f.input :end_xpath

  .form-actions
    = f.button :submit

app/views/bookmarks/edit.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



%h1 Editing bookmark

= render 'form'

= link_to 'Show', book_bookmark_path(@bookmark.book, @bookmark)
\|
= link_to 'Back', book_bookmarks_path(@bookmark.book)

app/views/bookmarks/index.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



%h1 Listing bookmarks

%table
  %tr
    %th Component
    %th Start_xpath
    %th
    %th
    %th

  - @bookmarks.each do |bookmark|
    %tr
      %td= bookmark.component_name
      %td= bookmark.start_xpath
      %td= link_to 'Show', book_bookmark_path(id: bookmark, book_id: bookmark.book_id)
      %td= link_to 'Edit', edit_book_bookmark_path(id: bookmark, book_id: bookmark.book_id)
      %td= link_to 'Destroy', book_bookmark_path(id: bookmark, book_id: bookmark.book_id), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Bookmark', new_book_bookmark_path

app/views/bookmarks/new.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



%h1 New bookmark

= render 'form'

= link_to 'Back', book_bookmarks_path(@bookmark.book)

app/views/bookmarks/show.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



%p#notice= notice

%p
  %b Component:
  = @bookmark.component_name
%p
  %b Start_xpath:
  = @bookmark.start_xpath

= link_to 'Edit', edit_book_bookmark_path(id: @bookmark, user_id: @user, book: @book)
\|
= link_to 'Back', book_bookmarks_path(user_id: @user, book: @book)