config/routes.rb
# encoding: utf-8

# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.


Tea::Application.routes.draw do

  root to: 'tea_sessions#new'
  match 'manifests/loader', to: 'manifests#loader'
  match 'manifests/reader.appcache', to: 'manifests#reader', format: :text

  devise_for :users
  resources :tea_sessions, only: [:new, :create, :destroy]

  namespace :ebook do
    match 'epub', to: 'epubs#reader', as: :epub_reader, format: :html
    match 'epub_sandbox', to: 'epubs#reader_sandbox', as: :epub_reader_sandbox, format: :html
    resources :epubs do
      resources :components, only: [:show], controller: 'epub/components'
      resources :chapters, only: [:index], controller: 'epub/chapters'
    end
  end

  scope :offline, as: :offline, path: :offline do
    namespace :ebook do
      match 'epub', to: 'epubs#reader', format: :html, offline: true
      match 'epub_sandbox', to: 'epubs#reader_sandbox', format: :html, offline: true
      match 'epubs', to: 'epubs#index', format: :html, offline: true
    end
  end

  resources :books do
    member do
      get :reading_position, to: 'reading_position#show'
      put :reading_position, to: 'reading_position#update'
    end
    resources :bookmarks
    resources :annotations, except: [:new, :edit]
  end

  devise_for :admins
  namespace :admin do
    root to: 'home#index'
    resources :booksellers
  end
  mount Resque::Server.new, at: "/resque", as: :resque

end

app/models/bookseller.rb
# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



class Bookseller
  include Mongoid::Document
  field :name
  field :bookstore_id
  field :domain
  field :catalog_url

  validates_presence_of :name, :bookstore_id, :domain, :catalog_url
  validates_uniqueness_of :name, :bookstore_id, :domain

  def stylesheet
    name = "customization_#{bookstore_id}"
    name if Tea::Application.assets.find_asset(name).present?
  end
end

app/controllers/admin/booksellers_controller.rb
# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



class Admin::BooksellersController < AdminController
  respond_to :html

  # GET /booksellers
  def index
    @booksellers = Bookseller.all
  end

  # GET /booksellers/1
  def show
    @bookseller = Bookseller.find(params[:id])
  end

  # GET /booksellers/new
  def new
    @bookseller = Bookseller.new
  end

  # POST /booksellers
  def create
    @bookseller = Bookseller.new(params[:bookseller])

    if @bookseller.save
      redirect_to [:admin, @bookseller], notice: 'Bookseller was successfully created.'
    else
      render action: "new"
    end
  end

  # GET /booksellers/1/edit
  def edit
    @bookseller = Bookseller.find(params[:id])
  end

  # PUT /booksellers/1
  def update
    @bookseller = Bookseller.find(params[:id])

    if @bookseller.update_attributes(params[:bookseller])
      redirect_to [:admin, @bookseller], notice: 'Bookseller was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /booksellers/1
  def destroy
    @bookseller = Bookseller.find(params[:id])
    @bookseller.destroy
    redirect_to admin_booksellers_url
  end
end

app/views/admin/booksellers/_form.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



= simple_form_for([:admin, @bookseller]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :bookstore_id, label: 'Bookstore ID'
    = f.input :domain
    = f.input :catalog_url

  .form-actions
    = f.button :submit

app/views/admin/booksellers/edit.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



%h1 Editing bookseller

= render 'form'

= link_to 'Show', [:admin, @bookseller]
\|
= link_to 'Back', admin_booksellers_path

app/views/admin/booksellers/index.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



%h1 Listing booksellers

%table
  %tr
    %th Name
    %th Bookstore ID
    %th Domain
    %th Catalog url
    %th
    %th
    %th

  - @booksellers.each do |bookseller|
    %tr
      %td= bookseller.name
      %td= bookseller.bookstore_id
      %td= bookseller.domain
      %td= bookseller.catalog_url
      %td= link_to 'Show', [:admin, bookseller]
      %td= link_to 'Edit', edit_admin_bookseller_path(bookseller)
      %td= link_to 'Destroy', [:admin, bookseller], :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Bookseller', new_admin_bookseller_path

app/views/admin/booksellers/new.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



%h1 New bookseller

= render 'form'

= link_to 'Back', admin_booksellers_path

app/views/admin/booksellers/show.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



%p#notice= notice

%p
  %b Name:
  = @bookseller.name
%p
  %b Bookstore ID:
  = @bookseller.bookstore_id
%p
  %b Domain:
  = @bookseller.domain
%p
  %b Catalog url:
  = @bookseller.catalog_url

= link_to 'Edit', edit_admin_bookseller_path(@bookseller)
\|
= link_to 'Back', admin_booksellers_path