config/routes.rb
# encoding: utf-8

# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.


Tea::Application.routes.draw do

  root to: 'tea_sessions#new'
  match 'manifests/loader', to: 'manifests#loader'
  match 'manifests/reader.appcache', to: 'manifests#reader', format: :text

  devise_for :users
  resources :tea_sessions, only: [:new, :create, :destroy]

  namespace :ebook do
    match 'epub', to: 'epubs#reader', as: :epub_reader, format: :html
    match 'epub_sandbox', to: 'epubs#reader_sandbox', as: :epub_reader_sandbox, format: :html
    resources :epubs do
      resources :components, only: [:show], controller: 'epub/components'
      resources :chapters, only: [:index], controller: 'epub/chapters'
    end
  end

  scope :offline, as: :offline, path: :offline do
    namespace :ebook do
      match 'epub', to: 'epubs#reader', format: :html, offline: true
      match 'epub_sandbox', to: 'epubs#reader_sandbox', format: :html, offline: true
      match 'epubs', to: 'epubs#index', format: :html, offline: true
    end
  end

  resources :books do
    member do
      get :reading_position, to: 'reading_position#show'
      put :reading_position, to: 'reading_position#update'
    end
    resources :bookmarks
    resources :annotations, except: [:new, :edit]
  end

  devise_for :admins
  namespace :admin do
    root to: 'home#index'
    resources :booksellers
  end
  mount Resque::Server.new, at: "/resque", as: :resque

end

app/models/ebook/base.rb
# encoding: utf-8

# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.


class Ebook::Base
  include Mongoid::Document
  include Mongoid::Timestamps

  field :api_id
  field :bookstore_id
  field :format, default: 'epub'
  field :title
  field :authors, type: Array, default: []
  field :publisher, type: Hash, default: {}
  field :subtitle
  field :language
  field :license, default: "none"
  field :descriptions, type: Array, default: []
  field :bytesize, type: Integer
  field :source
  field :direction

  mount_uploader :file, EbookUploader
  mount_uploader :cover, CoverUploader

  has_and_belongs_to_many :users, inverse_of: :books
  has_many :bookmarks,          inverse_of: :book,  dependent: :destroy
  has_many :annotations,        inverse_of: :book,  dependent: :destroy
  has_many :reading_positions,  inverse_of: :book,  dependent: :destroy

  scope :bookstore, ->(bookstore_id) { where(bookstore_id: bookstore_id)}

  after_destroy :clean_fs
  before_save :set_uploaded_state,  if: 'created?'

  validates_presence_of :format, :source

  # FIXME transitions logic
  state_machine initial: :created do
    event :uploaded do
      transition all => :uploaded
    end
    event :download_error do
      transition all => :download_error
    end
    event :extracting do
      transition all => :extracting
    end
    event :extracted do
      transition all => :extracted
    end
    event :extract_error do
      transition all => :extract_error
    end
    event :converting do
      transition all => :converting
    end
    event :converted do
      transition all => :converted
    end
    event :convert_error do
      transition all => :convert_error
    end
    after_transition on: :uploaded, do: :enqueue_extract_epub, if: lambda{|e| e.is_a? Ebook::Epub}
    after_transition on: :converted, do: :store_bytesize, if: lambda{|e| e.is_a? Ebook::Epub}
  end

  def to_param
    id.to_s
  end

  # Return the base directory path for this ebook
  #
  # @return String
  def base_dir_path
    File.join(Rails.root, file.store_dir)
  end

  # Create Ebook::Epub from TEA api
  # Later, this method will handle other types of Ebook, PDF for example
  #
  def self.create_from_api(json, user)
    json = json.with_indifferent_access
    json[:format].downcase!
    return unless json[:format].present?

    case json[:format]
      when 'epub'
        book = Ebook::Epub.find_or_initialize_from_api(json[:id])
        ReadingPosition.create_or_update_from_api(json[:id], user)
        book.user_ids << user.id
        cover_url = json.delete(:cover)
        book.remote_cover_url = cover_url if cover_url != book.remote_cover_url
        book.update_attributes json.slice(
          :bookstore_id, :title, :subtitle, :language, :license,
          :authors, :publisher, :descriptions
        )
        user.purchases[book.id.to_s]           = json[:purchase]
        user.number_of_bookmarks[book.id.to_s] = json[:number_of_bookmarks]
        user.save

        book
      else
        # FIXME Import pdf ?
        nil
      end
  end

  def tea_download_url
    if api_id
      Gaston.api.paths.download.gsub(':book_id', api_id)
    end
  end

  # Download Ebook file from the TEA API
  #
  def download!(cookie)
    hydra = Typhoeus::Hydra.hydra
    request = TeaApi::Request.build(
      url: tea_download_url,
      method: :get,
      cookie: cookie,
      follow_location: true,
      disable_ssl_host_verification: true, # FIXME ?
      disable_ssl_peer_verification: true  # FIXME ?
    )
    hydra.queue(request)
    request.on_complete do |response|
      case response.code
      when 200
        f = File.new "/tmp/#{self.id}.epub", 'wb'
        f.write response.body
        f.close
        self.file = File.open f
        self.save!
        File.delete f
      else
        Rails.logger.error "Fail to download #{self.title} : #{response.inspect}"
        self.download_error
      end
    end
    hydra.run
  end

  # Enqueue ebook download
  def enqueue_download(cookie)
    Resque.enqueue(DownloadEbookWorker, id, cookie)
  end

private

  def clean_fs
    FileUtils.rm_rf(base_dir_path)
    FileUtils.rm_rf(cover.store_dir) if cover.present?
  end

  def set_uploaded_state
    self.uploaded if self.file.present?
  end

end

app/models/ebook/epub/chapter.rb
# encoding: utf-8

# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.


class Ebook::Epub::Chapter
  include Mongoid::Document
  include Mongoid::Tree

  referenced_in :ebook, class_name: 'Ebook::Epub', inverse_of: :chapters

  field :title
  field :src
  field :position, type: Integer

  default_scope order_by([:position, :asc])

  # Create chapter and his children from a peregrin chapter
  #
  def self.create_chapter(ebook, chapter)
    root = Ebook::Epub::Chapter.create!(
      title: chapter.title,
      src: self.src_from_components(ebook, chapter),
      position: chapter.position,
      ebook: ebook
    )
    chapter.children.each do |child|
      root.children << Ebook::Epub::Chapter.create_chapter(ebook, child)
    end
    root
  end

  # FIXME UGLY
  # Chapters have path relative to nav or ncs file,
  # but components have path relative to opf file
  # We need to harmonize this for Monocle Chapters managment
  def self.src_from_components(ebook, chapter)
    match = /^.*#{chapter.src.gsub(/\#.*?$/, '')}.*/
    hash = chapter.src.gsub(/^([^#]*)/, '')
    src = ebook.components.where(src: match).first.try(:src)
    "#{src}#{hash}"
  end

  def as_json(options = {})
    options.merge!(methods: [:children])
    super(options)
  end
end

app/controllers/ebook/epub/chapters_controller.rb
# encoding: utf-8

# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.


# TODO spec
class Ebook::Epub::ChaptersController < ApplicationController
  respond_to :json

  # GET /ebook/epubs/1/chapters
  # GET /ebook/epubs/1/chapters.json
  def index
    @ebook = Ebook::Epub.find(params[:epub_id])
    respond_with @ebook.chapters.roots
  end
end

app/controllers/ebook/epub/components_controller.rb
# encoding: utf-8

# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



# TODO spec
class Ebook::Epub::ComponentsController < ApplicationController
  respond_to :json

  # GET /ebook/epubs/1/components/2
  # GET /ebook/epubs/1/components/2.json
  def show
    @component = components.find(params[:id])
    respond_with @component
  end

protected

  def components
    Ebook::Epub.find(params[:epub_id]).components
  end

end

app/controllers/ebook/epubs_controller.rb
# encoding: utf-8

# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



# TODO spec
class Ebook::EpubsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :fetch_book!, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /ebook/epubs
  # GET /ebook/epubs.json
  def index
    respond_to do |format|
      format.json {
        if current_bookseller.present?
          @ebooks = current_user.books.bookstore(current_bookseller.bookstore_id)
        else
          @ebooks = current_user.books
        end
        # FIXME UGLY !
        # TODO specs
        @ebooks.each do |e|
          e.set :purchase, current_user.purchases[e.id.to_s]
          e.set :reading_position, current_user.reading_position(e).as_json(minimal: true)
          e.set :number_of_bookmarks, (current_user.number_of_bookmarks[e.id.to_s]||0)
        end
        respond_with @ebooks.as_json(reading_position: true)
      }
      format.html{ import_user_books }
    end
  end

  # GET /ebook/epubs/1
  # GET /ebook/epubs/1.json
  def show
    respond_with @ebook.as_json(components: true, chapters: true)
  end

  # GET /ebook/epubs/new
  # GET /ebook/epubs/new.json
  def new
    @ebook = Ebook::Epub.new
    respond_with @ebook
  end

  # GET /ebook/epubs/1/edit
  def edit
    respond_with @ebook
  end

  # POST /ebook/epubs
  # POST /ebook/epubs.json
  def create
    @ebook = Ebook::Epub.new((params[:ebook_epub]||{}).merge(source: 'upload', format: 'epub'))
    @ebook.users << current_user

    respond_to do |format|
      if @ebook.save
        # TODO spec
        current_user.create_uploaded_purchase! @ebook
        format.html { redirect_to ebook_epubs_url, notice: 'Ebook::Epub was successfully created.' }
        format.json { render json: @ebook, status: :created, location: @ebook }
      else
        format.html { render action: "new" }
        format.json { render json: @ebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ebook/epubs/1
  # PUT /ebook/epubs/1.json
  def update
    respond_to do |format|
      if @ebook.update_attributes(params[:ebook_epub])
        format.html { redirect_to ebook_epubs_url, notice: 'Ebook::Epub was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ebook/epubs/1
  # DELETE /ebook/epubs/1.json
  def destroy
    @ebook.destroy

    respond_to do |format|
      format.html { redirect_to ebook_epubs_url }
      format.json { head :no_content }
    end
  end

  # GET /ebook/epub.html
  def reader
    render :reader, layout: false
  end

  # GET /ebook/epub_sandbox.html
  def reader_sandbox
    # TODO we should respond with the content-type "text/html-sandboxed"
    # when the supported browsers will accept it.
    # See http://www.w3.org/TR/2011/WD-html5-20110525/iana.html#text-html-sandboxed
    render :reader_sandbox, layout: false
  end

protected

  def fetch_book!
    @ebook = current_user.books.find(params[:id])
  end

  # Import user books if needed
  #
  def import_user_books
    session[:tea_sessions].each do |bookstore_id, cookie|
      # Sign out user if cookie is expire
      sign_out_and_redirect current_user and return unless bookstore_cookie bookstore_id
      if current_user.should_reimport_books?(bookstore_id)
        current_user.enqueue_import_books bookstore_cookie(bookstore_id), bookstore_id
      end
    end
  end

end

app/views/ebook/epubs/_form.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



= simple_form_for(@ebook) do |f|
  = f.error_notification

  .form-inputs
    - if @ebook.file?
      = @ebook.file_url
    - else
      = f.input :file, as: :file

  .form-actions
    = f.button :submit

app/views/ebook/epubs/edit.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



%h1 Editing ebook

= render 'form'

= link_to 'Show', @ebook
\|
= link_to 'Back', ebook_epubs_path

app/views/ebook/epubs/index.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



-#%header
  %p= link_to 'New Ebook', new_ebook_epub_path, class: 'btn btn-primary onlyOnline'

%section.content

app/views/ebook/epubs/new.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



%h1 New ebook

= render 'form'

= link_to 'Back', ebook_epubs_path

app/views/ebook/epubs/reader.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no")
    %title TeaBook Open Reader
    = stylesheet_link_tag "reader", :media => "all"
    = csrf_meta_tags
    /[if IE]
      = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js"

  %body(data-userid="#{current_user.id}")
    #reader
    = javascript_include_tag :reader

app/views/ebook/epubs/reader_sandbox.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %title TeaBook Open Reader
    = stylesheet_link_tag "reader_sandbox", :media => "all"

  %body(data-userid="#{current_user.id}")
    .loader
    = javascript_include_tag :reader_sandbox

app/views/ebook/epubs/show.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



%p#notice= notice


= link_to 'Edit', edit_ebook_epub_path(@ebook)
\|
= link_to 'Back', ebook_epubs_path