config/routes.rb
# encoding: utf-8

# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
# 
# This file is part of TeaBook Open Reader
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.0 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# An additional permission has been granted as a special exception 
# to the GNU General Public Licence. 
# You should have received a copy of this exception. If not, see 
# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.


Tea::Application.routes.draw do

  root to: 'tea_sessions#new'
  match 'manifests/loader', to: 'manifests#loader'
  match 'manifests/reader.appcache', to: 'manifests#reader', format: :text

  devise_for :users
  resources :tea_sessions, only: [:new, :create, :destroy]

  namespace :ebook do
    match 'epub', to: 'epubs#reader', as: :epub_reader, format: :html
    match 'epub_sandbox', to: 'epubs#reader_sandbox', as: :epub_reader_sandbox, format: :html
    resources :epubs do
      resources :components, only: [:show], controller: 'epub/components'
      resources :chapters, only: [:index], controller: 'epub/chapters'
    end
  end

  scope :offline, as: :offline, path: :offline do
    namespace :ebook do
      match 'epub', to: 'epubs#reader', format: :html, offline: true
      match 'epub_sandbox', to: 'epubs#reader_sandbox', format: :html, offline: true
      match 'epubs', to: 'epubs#index', format: :html, offline: true
    end
  end

  resources :books do
    member do
      get :reading_position, to: 'reading_position#show'
      put :reading_position, to: 'reading_position#update'
    end
    resources :bookmarks
    resources :annotations, except: [:new, :edit]
  end

  devise_for :admins
  namespace :admin do
    root to: 'home#index'
    resources :booksellers
  end
  mount Resque::Server.new, at: "/resque", as: :resque

end

app/views/layouts/_header.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



%nav
  %ul
    - if user_signed_in?
      %li.library= link_to 'Bibliothèque', ebook_epubs_path
      %li.catalog= link_to 'Librairie', current_bookseller.try(:catalog_url) || '#'

%p.logo
  %a.powered(href="/")
    %span powered by
    &#8216; tea &#8217;
    %span the ebook alternative

.rightZone
  = render partial: 'tea_sessions/links'

  .networkStatus

app/views/layouts/admin.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %title= content_for?(:title) ? yield(:title) : "TEA Administration"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    %link(href="/images/favicon.ico" rel="shortcut icon")

  %body(class="#{controller_name}_#{action_name}")

    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          %a.brand(href="/admin") TEA Administration
          .container.nav-collapse
            %ul.nav
              - unless admin_signed_in?
                %li= link_to "Sign in", new_admin_session_path
              - else
                %li= link_to "Libraires", admin_booksellers_path
                %li= link_to "Sign out", destroy_admin_session_path, method: :delete
    .container
      .content
        .row
          .span12
            - flash.each do |name, msg|
              %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
                %a.close{"data-dismiss" => "alert"} ×
                = msg
            = yield

    = javascript_include_tag "admin"

app/views/layouts/application.html.haml
-# Copyright (C) 2012  TEA, the ebook alternative <http://www.tea-ebook.com/>
-# 
-# This file is part of TeaBook Open Reader
-# 
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, version 3.0 of the License.
-# 
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-# 
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-# 
-# An additional permission has been granted as a special exception 
-# to the GNU General Public Licence. 
-# You should have received a copy of this exception. If not, see 
-# <https://github.com/TEA-ebook/teabook-open-reader/blob/master/GPL-3-EXCEPTION>.



!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no")
    %meta(http-equiv="X-UA-Compatible" content="chrome=1")

    %meta(name="apple-mobile-web-app-capable" content="yes")
    %meta(name="apple-touch-fullscreen" content="yes")
    %meta(name="apple-mobile-web-app-status-bar-style" content="transparent")
    %link(rel="apple-touch-icon" href="/assets/icon.png")

    %title= content_for?(:title) ? yield(:title) : "TeaBook Open Reader"
    = bookseller_stylesheet
    = csrf_meta_tags
    /[if IE]
      = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js"
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"

  %body(class="#{controller_name}_#{action_name}" data-userid="#{current_user.id if user_signed_in?}" data-online="#{online?}" data-bookstore="#{current_bookseller.try(:bookstore_id)}")

    %header
      = render partial: 'layouts/header'

    %section.container
      - if user_signed_in?
        .modal.account.hide#account(style="display: none;")
          %header
            <h1>Mon compte</h1>
            <button class="close" data-dismiss="modal">×</button>
          %section
            %ul
              - if @current_bookseller.present?
                - if !bookstore_session
                  %li= link_to "Connectez-vous", new_tea_session_path
                - else
                  %li
                    Connecté en tant que #{current_user.account(@current_bookseller.bookstore_id)['email']}
                    = link_to "Déconnectez-vous", tea_session_path(id: @current_bookseller.bookstore_id), method: :delete
              - else
                - session[:tea_sessions].each do |key, value|
                  %li
                    Connecté en tant que #{current_user.account(key)['email']}
                    = link_to "Déconnectez-vous de #{key}", tea_session_path(id: key), method: :delete, class: :btn

      - flash.each do |name, msg|
        %article{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
          %a.close{"data-dismiss" => "alert"} ×
          %p= msg

      = yield
      #help

    = javascript_include_tag "application"